repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
        # regression test files should never be touched
        exclude: ^tests/test_.*/.*
      - id: trailing-whitespace
        exclude: ^tests/test_.*/.*
      - id: destroyed-symlinks
      - id: check-yaml
      - id: check-added-large-files
