# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  push:
    tags:
      - "20*.*.*"

jobs:
  pypi:
    name: PyPi Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # to guarantee proper versioneer pickup of last tag
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Build dist artefacts
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build
        python -m build --sdist --wheel --outdir dist/
    - name: Test wheel
      run: |
        pip install dist/ontoviz*whl
        ontoviz_to_dot --help
    - name: Print version
      run: |
        python -c "import ontoviz;print(ontoviz.__version__)"
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.3
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
  github:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: true
        prerelease: false
